//[]
--select
DECLARE @IDORDEN INT
SELECT TOP 1 C.*, M.CODIGO AS CODIGOMONEDA FROM CONTROL.VENTAS.DBO.CARRITO c,
CONTROL.VENTAS.DBO.monedas M
WHERE  C.IDEMPRESA = <#SESSION.IDEMPRESA/> and C.idproducto=1
and c.idMONEDA = M.idmoneda
 ORDER BY 1 DESC
