//[session.db|Untyped,session.idusuario|Untyped,]
--select 





select UA.IDUSUARIOALERTA, US.IDMETA
from <#SESSION.DB/>.DBO.USUARIOS_ALERTAS UA
JOIN <#SESSION.DB/>.DBO.USUARIOS_SUCESOS US ON US.IDSUCESO = UA.IDSUCESO 
where UA.idusuario=<#SESSION.IDUSUARIO/> and UA.LEIDO=0 AND UA.NOTIFICADO=0 and US.TIPO=19 



UPDATE UA SET NOTIFICADO = 1
from <#SESSION.DB/>.DBO.USUARIOS_ALERTAS UA
JOIN <#SESSION.DB/>.DBO.USUARIOS_SUCESOS US ON US.IDSUCESO = UA.IDSUCESO 
where UA.idusuario=<#SESSION.IDUSUARIO/> and UA.LEIDO=0 AND UA.NOTIFICADO=0 and (US.TIPO=19 OR US.TIPO = 69) 

DECLARE  @METASALCANZADAS INT, @METASNOALCANZADAS INT


select @METASALCANZADAS = COUNT(*)
from DBO.USUARIOS_ALERTAS UA  WITH(NOLOCK)
JOIN DBO.USUARIOS_SUCESOS US   WITH(NOLOCK) ON US.IDSUCESO = UA.IDSUCESO 
where UA.idusuario=@IDUSUARIO and UA.LEIDO=0 AND UA.NOTIFICADO=0 and US.TIPO=19

select @METASNOALCANZADAS = COUNT(*)
from DBO.USUARIOS_ALERTAS UA  WITH(NOLOCK)
JOIN DBO.USUARIOS_SUCESOS US   WITH(NOLOCK) ON US.IDSUCESO = UA.IDSUCESO 
where UA.idusuario=@IDUSUARIO and UA.LEIDO=0 AND UA.NOTIFICADO=0 and US.TIPO=69



IF  (@METASALCANZADAS!=0)
  INSERT INTO SALESUP_CT.dbo.SQS  (IDUSUARIO, ALERTA, VALOR) VALUES (<#SESSION.IDUSUARIO/> , 'metasAlcanzadas', @METASALCANZADAS*-1)

IF  (@METASNOALCANZADAS!=0)
  INSERT INTO SALESUP_CT.dbo.SQS  (IDUSUARIO, ALERTA, VALOR) VALUES (<#SESSION.IDUSUARIO/> , 'metasNoAlcanzadas', @METASNOALCANZADAS*-1)
