//[condicion|Text,idetiqueta|Integer,idautoresponder|Integer,session.idempresa|Untyped,tk|Text,session.db|Untyped,tkauto|Text,]
--SELECT
/*PROTEGIDOS*/
DECLARE @CONDICION VARCHAR(MAX)
SET @CONDICION = ISNULL(:CONDICION,'')


DECLARE @IDETIQUETA INT, @IDAUTORESPONDER INT, @IDEMPRESA INT
DECLARE @TKAUTO VARCHAR(128)
DECLARE @TK VARCHAR(128)
DECLARE @SQL VARCHAR(MAX)

SET @IDETIQUETA = ISNULL(:IDETIQUETA,0)
SET @IDAUTORESPONDER = ISNULL(:IDAUTORESPONDER,0)
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

SET @TK = ISNULL(:TK,'')
IF @TK != '' BEGIN SELECT @IDETIQUETA=IDETIQUETA FROM <#SESSION.DB/>.DBO.ETIQUETAS WHERE CAST(TK AS VARCHAR(128))  = @TK AND IDEMPRESA =@IDEMPRESA END


SET @TKAUTO = ISNULL(:TKAUTO,'')
IF @TKAUTO != '' BEGIN SELECT @IDAUTORESPONDER=IDAUTORESPONDER FROM <#SESSION.DB/>.DBO.AUTORESPONDERS WHERE CAST(TKAUTO AS VARCHAR(128))  = @TKAUTO AND IDEMPRESA = @IDEMPRESA END

EXEC <#SESSION.DB/>.DBO.SP_CORREOS_AUTORESPONDERS_DETALLE @IDETIQUETA,@IDAUTORESPONDER,@IDEMPRESA,@TK,@TKAUTO,@CONDICION
