//[session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,componente|Integer]

--SELECT

DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @COMPONENTE INT = ISNULL(:COMPONENTE,1)
DECLARE @SQLTXT VARCHAR(MAX) = ''
DECLARE @WHERE VARCHAR(MAX) = ''

IF @COMPONENTE > 0
BEGIN
	 SET @WHERE = 'IDCOMPONENTE = '+CAST(@COMPONENTE AS VARCHAR(MAX))+' AND'
END
ELSE BEGIN SET @WHERE = '' END

SET @SQLTXT = 'SELECT COUNT(1) AS CANTMETAS
FROM <#SESSION.DB/>.DBO.USUARIOS_METAS (NOLOCK)
WHERE 
	IDUSUARIO_ASIGNO = '+CAST(@IDUSUARIO AS VARCHAR(MAX))+' AND
	IDEMPRESA = '+CAST(@IDEMPRESA AS VARCHAR(MAX))+' AND
	STATUS = 1 AND ' 
SET @SQLTXT = @SQLTXT + @WHERE
SET @SQLTXT = @SQLTXT + ' INICIO ='''+CAST(YEAR(GETDATE()) AS VARCHAR(4))+''+CAST(MONTH(GETDATE()) AS VARCHAR(2))+'01'''

EXEC(@SQLTXT)