//[tipo_consulta|Text,session.db|Untyped,session.idempresa|Untyped,]
-- select 

DECLARE @TIPO_CONSULTA INT
DECLARE @TIPO_CAMPOS VARCHAR(2)
DECLARE @TIPOCAMPO INT, @COMPARTIR INT, @IDEMPRESA INT

SET @IDEMPRESA = CAST('<#session.idempresa/>' AS INT)
SET @TIPO_CONSULTA = CAST(:TIPO_CONSULTA AS INT) 

/* -2 Todos Activos */
/* -1 Todos Incluye descartados */
/* 1 Sólo prospectos */
/* 4 Sólo descartados */
/* 2 Sólo oportunidades */
/* 3 Sólo ventas */
/* 5 Sólo clientes */

SET @TIPOCAMPO = CASE WHEN @TIPO_CONSULTA IN (-1, -2, 1, 4) THEN 1 
				 	  WHEN @TIPO_CONSULTA = 5 THEN 3
					  WHEN @TIPO_CONSULTA = 2 THEN 2
				 	  WHEN @TIPO_CONSULTA = 3 THEN 4
			 	 END

SET @COMPARTIR = CASE WHEN @TIPO_CONSULTA IN (-1, -2, 1, 4) THEN 3 
				 	  WHEN @TIPO_CONSULTA = 5 THEN 1
					  WHEN @TIPO_CONSULTA = 2 THEN 4
				 	  WHEN @TIPO_CONSULTA = 3 THEN 2
			 	 END
			 	   
SET @TIPO_CAMPOS = CASE WHEN @TIPO_CONSULTA IN (-1, -2, 1, 4, 5) THEN 'P'
					    WHEN @TIPO_CONSULTA IN (2,3) THEN 'O'
			 	   END

SELECT CASE WHEN TIPO = 5 THEN 'CCAMPO' ELSE 'CAMPO' END + CAST(INDICE AS VARCHAR(2)) + CASE WHEN TIPO = 5 THEN '' ELSE @TIPO_CAMPOS END AS ELCAMPO
FROM <#SESSION.DB/>.DBO.EMPRESAS_CAMPOS
WHERE IDEMPRESA = @IDEMPRESA AND (TIPO = @TIPOCAMPO OR COMPARTIR = @COMPARTIR) 
ORDER BY TIPO, INDICE DESC

