//[session.idusuario|Untyped,session.db|Untyped,session.idempresa|Untyped,configuracion|Text,tk|Text]
--select
DECLARE @idusuario VARCHAR(MAX)
DECLARE @idempresa VARCHAR(MAX)

DECLARE @CATEGORIA INT
DECLARE @IDS INT

DECLARE @IDSUSUARIOS VARCHAR(MAX) = ''
DECLARE @SQL VARCHAR(MAX) = ''
DECLARE @IDSCOMPANIAS VARCHAR(MAX) = ''


SELECT @IDSCOMPANIAS = CAST(ID AS VARCHAR(1000))+','+@IDSCOMPANIAS FROM <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulosEmpresas(<#session.idusuario/>,<#session.idempresa/>, 17)

SET @IDSCOMPANIAS = @IDSCOMPANIAS + '0'

SELECT	
@IDSUSUARIOS=CAST(ID AS VARCHAR(1000))+','+@IDSUSUARIOS 
FROM 
	SALESUP_DB8.DBO.ObtieneUsuariosAutorizadosModulos (<#session.idusuario/>,1,0) 

	SET @IDSUSUARIOS = @IDSUSUARIOS + '0'


SET @idusuario = <#session.idusuario/>
SET @idempresa = <#session.idempresa/>

SELECT @CATEGORIA = TI.CATEGORIA, @IDS = TI.IDINCONSISTENCIA FROM SALESUP_CT.DBO.TIPOS_INCONSISTENCIA TI WHERE tk = '<#TK/>'

EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_INCONSISTENCIA @IDS,@CATEGORIA, @idempresa

SET @SQL = '
SELECT 
	CAST(TI.TK AS VARCHAR(MAX)) AS TK, TI.INCONSISTENCIA, TI.CATEGORIA, COUNT(P.IDPROSPECTO) AS TOTAL 
FROM
	<#SESSION.DB/>.DBO.FN_INCONSISTENCIASACTIVAS(<#SESSION.IDEMPRESA/>,<#SESSION.IDUSUARIO/>,1) FIA
	JOIN SALESUP_CT.DBO.TIPOS_INCONSISTENCIA TI WITH (NOLOCK) ON TI.IDINCONSISTENCIA = FIA.IDINCONSISTENCIA 
	LEFT JOIN <#SESSION.DB/>.DBO.REGISTRO_INCONSISTENCIA RI WITH (NOLOCK) ON RI.IDINCONSISTENCIA = TI.IDINCONSISTENCIA
	LEFT  JOIN <#SESSION.DB/>.DBO.PROSPECTOS P WITH (NOLOCK) ON RI.IDPROSPECTO = P.IDPROSPECTO AND P.IDUSUARIO IN('+@IDSUSUARIOS+') AND P.IDEMPRESA = RI.IDEMPRESA AND P.IDEMPRESA = <#SESSION.IDEMPRESA/>
	WHERE TI.TK = ''<#TK/>''
GROUP BY 
	TI.TK, TI.IDINCONSISTENCIA, TI.INCONSISTENCIA, TI.CATEGORIA
UNION
SELECT 
	CAST(TI.TK AS VARCHAR(MAX)) AS TK, TI.INCONSISTENCIA, TI.CATEGORIA, COUNT(C.IDCOMPANIA) AS TOTAL 
FROM
	<#SESSION.DB/>.DBO.FN_INCONSISTENCIASACTIVAS(<#SESSION.IDEMPRESA/>,<#SESSION.IDUSUARIO/>,2) FIA
	JOIN SALESUP_CT.DBO.TIPOS_INCONSISTENCIA TI WITH (NOLOCK) ON TI.IDINCONSISTENCIA = FIA.IDINCONSISTENCIA 
	LEFT JOIN <#SESSION.DB/>.DBO.REGISTRO_INCONSISTENCIA RI WITH (NOLOCK) ON RI.IDINCONSISTENCIA = TI.IDINCONSISTENCIA
	LEFT JOIN <#SESSION.DB/>.DBO.COMPANIAS C WITH (NOLOCK) ON RI.IDCOMPANIA = C.IDCOMPANIA AND C.IDEMPRESA = <#SESSION.IDEMPRESA/> 
	LEFT JOIN USUARIOS U WITH (NOLOCK) ON U.IDUSUARIO = C.IDUSUARIO AND U.IDUSUARIO IN ('+@IDSCOMPANIAS+')
	WHERE TI.TK = ''<#TK/>''
GROUP BY 
	TI.TK, TI.IDINCONSISTENCIA, TI.INCONSISTENCIA, TI.CATEGORIA ORDER BY TOTAL DESC
'


EXEC (@SQL)