//[TKU|Text,TKREN|Text]
--SELECT

DECLARE @TKU Varchar(MAX) 
DECLARE @TKREN Varchar(MAX) 

SET @TKU = ISNULL(:TKU,'')
SET @TKREN = ISNULL(:TKREN,'')

EXEC SALESUP_CT.DBO.SP_CANCELA_ELIMINACION @TKU,@TKREN
