//[start|Integer,howmany|Integer,session.idusuario|Untyped,session.db|Untyped,session.idempresa|Untyped,TK|Text,TKCOM|Text]
--SELECT

DECLARE @TK VARCHAR(128) = :TK
DECLARE @START INT 
DECLARE @HOWMANY INT
DECLARE @TOP VARCHAR(MAX)
SET @START = :START
SET @HOWMANY = :HOWMANY
SET @TOP= ''

IF @START IS NOT NULL AND @HOWMANY IS NOT NULL
BEGIN 
	  SET @TOP= 'TOP '+CAST(ISNULL(@START+@HOWMANY-1,50) AS VARCHAR(MAX))
END


EXEC  <#session.db/>.dbo.SP_DETALLE_INCONSISTENCIA @TK, <#SESSION.IDEMPRESA/>, <#SESSION.IDUSUARIO/>, @TOP
