//[session.idempresa|Untyped,session.idusuario|Untyped,session.db|Untyped]
--DELETE

DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @IDREGISTROELIMINACION INT

SET @IDEMPRESA = CAST(<#SESSION.IDEMPRESA/> AS INT)
SET @IDUSUARIO = CAST(<#SESSION.IDUSUARIO/> AS INT)

SELECT @IDREGISTROELIMINACION = IDREGISTRO_ELIMINACION FROM <#SESSION.DB/>.dbo.REGISTRO_ELIMINACIONES WHERE IDUSUARIO = @IDUSUARIO AND IDEMPRESA = @IDEMPRESA

DELETE FROM <#SESSION.DB/>.dbo.REGISTRO_ELIMINACIONES_NOTIFICACIONES WHERE IDREGISTRO_ELIMINACION = @IDREGISTROELIMINACION
DELETE FROM <#SESSION.DB/>.dbo.REGISTRO_ELIMINACIONES_DETALLE WHERE IDREGISTRO_ELIMINACION = @IDREGISTROELIMINACION
DELETE FROM <#SESSION.DB/>.dbo.REGISTRO_ELIMINACIONES WHERE IDREGISTRO_ELIMINACION = @IDREGISTROELIMINACION