//[ltInvitados|Text,ltTiposInvitados|Text,session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,]
--SELECT
DECLARE @IDPERSONAS VARCHAR(MAX)
DECLARE @TIPOSPERSONAS VARCHAR(MAX)
DECLARE @TABLAPERSONAS AS TABLE (ID INT, IDPERSONA INT, PERSONA VARCHAR(1000), TIPOPERSONA INT)

SET @IDPERSONAS=ISNULL(:ltInvitados,'')
SET @TIPOSPERSONAS=ISNULL(:ltTiposInvitados,'')
--SET @IDPERSONAS = 'P-BD965E0B-5D9F-449F-9CFE-4FF7D31D4AE5,U-B66F2060-0A61-4CFE-AD7B-3C1C171415AC' 
-- SET @TIOSPERSONAS= '1,2'

INSERT INTO @TABLAPERSONAS (ID,IDPERSONA,PERSONA,TIPOPERSONA)
SELECT
P.OCCURENCEID AS ID, 
(
	CASE T.SPLITVALUE
		WHEN 1 THEN <#SESSION.DB/>.dbo.obtieneIdProspecto(P.SPLITVALUE, <#SESSION.IDEMPRESA/>)
		WHEN 2 THEN SALESUP_CT.dbo.obtieneIdUsuario(P.SPLITVALUE)
		ELSE 0
	END
) IDPERSONA, 
(CASE WHEN T.SPLITVALUE=0 THEN P.SPLITVALUE ELSE '' END) PERSONA,
T.SPLITVALUE AS TIPOPERSONA
FROM dbo.Split(@IDPERSONAS,',') P, dbo.Split(@TIPOSPERSONAS,',') T  
WHERE P.OCCURENCEID=T.OCCURENCEID 

--SELECT * FROM @TABLAPERSONAS AS TABLAPERSONA

IF (LEN(RTRIM(LTRIM(@IDPERSONAS)))>0)
BEGIN
  SELECT 
   2 AS LE,'Colaboradores' as grupo,U.TKU AS tk,    
			'' AS Titulo , LTRIM(RTRIM(U.NOMBRE)) AS Nombre ,    
			<#SESSION.DB/>.dbo.NomalizaCadena(LTRIM(RTRIM(U.NOMBRE))) AS NomNorma,    
			ISNULL(LTRIM(RTRIM(U.APELLIDOS)),'') AS Apellido ,    
			<#SESSION.DB/>.dbo.NomalizaCadena(ISNULL(LTRIM(RTRIM(U.APELLIDOS)),'''')) AS ApeNorma,    
			'' AS Empresa, U.EMAIL AS Correo, '''' AS Sexo,    
			'' + '' AS Telefono, '' AS Movil,    
			'' AS Region,    
			0 EsCliente , LTRIM(RTRIM(U.INICIALES)) AS Iniciales,'' AS direccion1,'' AS direccion2  

   from <#SESSION.DB/>.dbo.USUARIOS U where  U.IDEMPRESA=<#SESSION.IDEMPRESA/> 
   -- from dbo.USUARIOS U where  U.IDEMPRESA=26122
   /*AND U.IDUSUARIO IN (SELECT ID from <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos(<#SESSION.IDUSUARIO/>,5,0))  */  
   UNION
   SELECT 1 AS LE,'Contactos' as grupo, P.TKP AS tk, 
		ISNULL(P.TITULO+' ','') AS Titulo , LTRIM(RTRIM(P.NOMBRE)) AS Nombre , 
		<#SESSION.DB/>.dbo.NomalizaCadena(LTRIM(RTRIM(P.NOMBRE))) AS NomNorma, 
		ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'') AS Apellido , 
		<#SESSION.DB/>.dbo.NomalizaCadena(ISNULL(LTRIM(RTRIM(P.APELLIDOS)),'')) AS ApeNorma, 
		P.EMPRESA AS Empresa, P.CORREO AS Correo, P.SEXO AS Sexo, 
		ISNULL(P.TELEFONO,'') + ISNULL(', '+P.TELEFONO2,'') AS Telefono, ISNULL(P.MOVIL,'') AS Movil, 
		ISNULL(E.ESTADO+', ','')+ ISNULL(PAI.PAIS,'') AS Region, 
		P.ESCLIENTE AS EsCliente , LTRIM(RTRIM(U.INICIALES)) AS Iniciales,
		<#SESSION.DB/>.DBO.FormatoDireccion((P.DIRECCION1+' '+P.DIRECCION2+', '+P.CIUDAD+', '+P.IDESTADO+', '+P.CODIGOPOSTAL )) AS direccion1,
  	    <#SESSION.DB/>.DBO.FormatoDireccion((C.DIRECCION1+' '+C.DIRECCION2+', '+C.CIUDAD+', '+C.IDESTADO+', '+C.CODIGOPOSTAL )) AS direccion2 
		-- DBO.FormatoDireccion((P.DIRECCION1+' '+P.DIRECCION2+', '+P.CIUDAD+', '+P.IDESTADO+', '+P.CODIGOPOSTAL )) AS direccion1,
  	    -- DBO.FormatoDireccion((C.DIRECCION1+' '+C.DIRECCION2+', '+C.CIUDAD+', '+C.IDESTADO+', '+C.CODIGOPOSTAL )) AS direccion2 
	 FROM  <#SESSION.DB/>.DBO.PROSPECTOS_ASIGNADOS PA, <#SESSION.DB/>.dbo.PROSPECTOS P 
	 -- FROM  DBO.PROSPECTOS_ASIGNADOS PA, dbo.PROSPECTOS P 
	    LEFT JOIN <#SESSION.DB/>.dbo.COMPANIAS C ON C.IDCOMPANIA=P.IDCOMPANIA 
		LEFT JOIN <#SESSION.DB/>.dbo.PAISES PAI ON PAI.IDPAIS=P.IDPAIS 
		LEFT JOIN <#SESSION.DB/>.dbo.ESTADOS E ON PAI.IDPAIS=E.IDPAIS AND E.IDESTADO=P.IDESTADO 
		LEFT JOIN <#SESSION.DB/>.dbo.USUARIOS U ON U.IDUSUARIO = P.IDUSUARIO 
		-- LEFT JOIN dbo.COMPANIAS C ON C.IDCOMPANIA=P.IDCOMPANIA 
		-- LEFT JOIN dbo.PAISES PAI ON PAI.IDPAIS=P.IDPAIS 
		-- LEFT JOIN dbo.ESTADOS E ON PAI.IDPAIS=E.IDPAIS AND E.IDESTADO=P.IDESTADO 
		-- LEFT JOIN dbo.USUARIOS U ON U.IDUSUARIO = P.IDUSUARIO 
	  WHERE P.IDEMPRESA = <#SESSION.IDEMPRESA/> AND P.DESCARTADO = 0 AND P.IDPROSPECTO=PA.IDPROSPECTO AND P.IDPROSPECTO IN (SELECT IDPERSONA FROM @TABLAPERSONAS WHERE TIPOPERSONA=1)
	  -- WHERE P.IDEMPRESA = 26122 AND P.DESCARTADO = 0 AND P.IDPROSPECTO=PA.IDPROSPECTO AND P.IDPROSPECTO IN (SELECT IDPERSONA FROM @TABLAPERSONAS WHERE TIPOPERSONA=1) 
 
   ORDER BY LE DESC
END
ELSE
BEGIN
SELECT 
   2 AS LE,'Colaboradores' as grupo,U.TKU AS tk,
			'' AS Titulo , LTRIM(RTRIM(U.NOMBRE)) AS Nombre ,    
			dbo.NomalizaCadena(LTRIM(RTRIM(U.NOMBRE))) AS NomNorma,    
			ISNULL(LTRIM(RTRIM(U.APELLIDOS)),'') AS Apellido ,    
			dbo.NomalizaCadena(ISNULL(LTRIM(RTRIM(U.APELLIDOS)),'''')) AS ApeNorma,    
			'' AS Empresa, U.EMAIL AS Correo, '''' AS Sexo,    
			'' + '' AS Telefono, '' AS Movil,    
			'' AS Region,    
			0 EsCliente , LTRIM(RTRIM(U.INICIALES)) AS Iniciales,'' AS direccion1,'' AS direccion2  

from <#SESSION.DB/>.dbo.USUARIOS U where U.IDEMPRESA=<#SESSION.IDEMPRESA/> 
-- from dbo.USUARIOS U where U.IDEMPRESA=26122
/*AND U.IDUSUARIO IN (SELECT ID from <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizadosModulos(<#SESSION.IDUSUARIO/>,5,0)) */
ORDER BY U.NOMBRE, U.APELLIDOS ASC
END