//[idusuarioalerta|Integer,session.db|Untyped,]
--select
/*PROTEGIDO*/
/*SEP2015*/
DECLARE @IDUSUARIOALERTA INT
DECLARE @LINK VARCHAR(128)
SET @IDUSUARIOALERTA = ISNULL(:IDUSUARIOALERTA,0)
SET @LINK = <#SESSION.DB/>.DBO.ObtieneLinkAlerta(@IDUSUARIOALERTA);
UPDATE <#SESSION.DB/>.DBO.USUARIOS_ALERTAS SET LEIDO = 1, NOTIFICADO = 1 WHERE IDUSUARIOALERTA = @IDUSUARIOALERTA

INSERT INTO SALESUP_CT.dbo.SQS (IDUSUARIO, ALERTA, VALOR) VALUES (<#SESSION.IDUSUARIO/>, 'notificaciones',-1 )

SELECT @LINK AS Link
