//[start|Integer,howmany|Integer,idpantalla|Integer,session.db|Untyped,session.idempresa|Untyped,session.idusuario|Untyped,session.nivel|Untyped,session.idgrupo|Untyped,session.mailconfig|Untyped,checkempresa|Integer,total|Integer]
--SELECT 

DECLARE @TOP VARCHAR(MAX)
DECLARE @CHECKEMPRESA INT 
DECLARE @START INT 
DECLARE @HOWMANY INT 
DECLARE @IDPANTALLA INT
DECLARE @ELIMINARDATOS INT
DECLARE @TOTAL INT

SET @TOTAL = ISNULL(:total,'')
SET @ELIMINARDATOS = 0
SET @START = :START
SET @HOWMANY = :HOWMANY
SET @TOP= ''
SET @CHECKEMPRESA = ISNULL(:checkempresa,0)
SET @IDPANTALLA = ISNULL(:IDPANTALLA,1)


IF @START IS NOT NULL AND @HOWMANY IS NOT NULL
BEGIN 
	  SET @TOP= 'TOP '+CAST(ISNULL(@START+@HOWMANY-1,50) AS VARCHAR(MAX))
END


 
DECLARE @IDEMPRESA INT , @IDUSUARIO INT, @NIVELUSUARIO INT, @IDGRUPO INT, @MAILCONFIG INT
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @NIVELUSUARIO = <#SESSION.NIVEL/>
SET @IDGRUPO = <#SESSION.IDGRUPO/>
SET @MAILCONFIG = <#SESSION.MAILCONFIG/>

EXEC <#SESSION.DB/>.DBO.SP_DESCARTADOSPARAELIMINACION @TOP,@IDPANTALLA,@IDEMPRESA,@IDUSUARIO,@NIVELUSUARIO,@MAILCONFIG,@CHECKEMPRESA,@ELIMINARDATOS,''