//[session.db|Untyped,idpeticion|Text,listap|Text,session.idempresa|Untyped,tkp|Text,session.idusuario|Untyped,session.convertcode|Untyped,idusuario|Integer,comentario|Text,tieneoportunidad|Text,conservar_oportunidades|Text,tku|Text]
--update
	
IF  NOT EXISTS (SELECT IDPETICION FROM <#SESSION.DB/>.dbo.USUARIOS_SUCESOS WITH(ROWLOCK) WHERE  FECHAHORA > GETDATE()-1 AND IDPETICION != '' AND IDPETICION = :IDPETICION)
BEGIN 
DECLARE @IDPROSPECTO INT
DECLARE @TOTALPROSPECTOS INT
DECLARE @TABLATEMP TABLE (ID INT IDENTITY, IDPROSPECTO INT)
DECLARE @TO INT, @TOTAL INT
DECLARE @LISTA VARCHAR(MAX)
DECLARE @DUENIO INT
DECLARE @IDEMPRESA INT
DECLARE @TKP VARCHAR(MAX)
DECLARE @TKU VARCHAR(MAX)
DECLARE @ELIDUSUARIO INT


SET @TO = 1
SET @LISTA = :LISTAP
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>
SET @TKP = ISNULL(:TKP,'')
SET @TKU = ISNULL(:TKU, '')

SET @ELIDUSUARIO = <#SESSION.DB/>.DBO.REGRESAIDUSUARIO(@TKU)

IF @TKP != '' 
BEGIN
   SET @LISTA = ''
   SET @LISTA = <#SESSION.DB/>.dbo.obtieneListaIdProspecto(@TKP, @IDEMPRESA)
END



SELECT @TOTALPROSPECTOS = COUNT(*) 
FROM <#SESSION.DB/>.dbo.PROSPECTOS WITH(NOLOCK) 
WHERE IDPROSPECTO IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.dbo.SPLIT(@LISTA,','))
AND IDEMPRESA  = <#SESSION.IDEMPRESA/> 



INSERT INTO @TABLATEMP (IDPROSPECTO)
SELECT IDPROSPECTO FROM <#SESSION.DB/>.dbo.PROSPECTOS WITH(NOLOCK) WHERE IDPROSPECTO IN (SELECT SPLITVALUE FROM <#SESSION.DB/>.dbo.SPLIT(@LISTA,',')) 

SELECT @TOTAL = COUNT(*)  FROM @TABLATEMP

WHILE @TO <= @TOTAL
BEGIN
   SELECT @IDPROSPECTO = IDPROSPECTO FROM @TABLATEMP WHERE ID = @TO
   SELECT @DUENIO = IDUSUARIO FROM <#SESSION.DB/>.dbo.PROSPECTOS WHERE IDPROSPECTO = @IDPROSPECTO
   
   INSERT INTO <#SESSION.DB/>.dbo.USUARIOS_SUCESOS WITH(ROWLOCK) (IDUSUARIO,FECHAHORA,TIPO,TEXTO,IDPROSPECTO,IDUSUARIO_DESTINO, IDPETICION) 
   VALUES (<#SESSION.IDUSUARIO/>,CONVERT(DATETIME,GetDate(),<#SESSION.CONVERTCODE/>),5,'Se ha reasignado el prospecto',@IDPROSPECTO,@ELIDUSUARIO, :IDPETICION)
   EXEC <#SESSION.DB/>.dbo.SP_REASIGNAR_PROSPECTO @IDPROSPECTO,@ELIDUSUARIO,<#SESSION.IDUSUARIO/>, :COMENTARIO, @TOTALPROSPECTOS
   EXEC <#SESSION.DB/>.dbo.SP_ACTUALIZA_METAS 1, @ELIDUSUARIO
   EXEC <#SESSION.DB/>.dbo.SP_ACTUALIZA_METAS 1, <#SESSION.IDUSUARIO/>
   
   UPDATE <#SESSION.DB/>.dbo.PROSPECTOS SET ULTIMAMODIFICACION = GETDATE(), CAMBIOLOCAL=2 WHERE IDPROSPECTO = @IDPROSPECTO
   
   IF (:tieneOportunidad = '1')
   BEGIN
   
   		IF (:conservar_oportunidades = '1')
	 	 BEGIN
	 	  
	   	  	   INSERT INTO <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS WITH(ROWLOCK) (IDUSUARIO,IDPROSPECTO,ARCHIVADO) VALUES (@DUENIO,@IDPROSPECTO,0)
			   
			   UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET ULTIMAMODIFICACION = GETDATE(), CAMBIOLOCAL=2 WHERE IDPROSPECTO = @IDPROSPECTO
   			   UPDATE  <#SESSION.DB/>.DBO.prospectos_seguimiento SET ultimamodificacion=GETDATE() WHERE IDSEGUIMIENTO IN (SELECT TOP (10) IDSEGUIMIENTO FROM <#SESSION.DB/>.DBO.prospectos_seguimiento WHERE idprospecto=@IDPROSPECTO ORDER BY 1 DESC)
   	 
	 	 	   DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDTABLA = 5 AND IDUSUARIO = @DUENIO
	 		   INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDTABLA,IDUSUARIO,FECHAHORA) VALUES (5,@DUENIO,GETDATE())

		END
	 	ELSE
	 	BEGIN
		   /*VARIABLE CANALIZACION*/
		   DECLARE @CAMBIOLOCAL INT, @ESCANALIZADO VARCHAR(2)
		   SET @IDEMPRESA = CAST('<#SESSION.IDEMPRESA/>' AS INT)
		   SELECT @ESCANALIZADO = SALESUP_CT.dbo.esCanalizado(P.TKP, P.TKPM) FROM <#SESSION.DB/>.dbo.PROSPECTOS P WHERE P.IDPROSPECTO = @IDPROSPECTO AND P.IDEMPRESA = @IDEMPRESA
  		   IF @ESCANALIZADO = '1' OR @ESCANALIZADO = '2' BEGIN SET @CAMBIOLOCAL = 1 END
  		   /*FIN VARIABLE CANALIZACION*/
		   
	 	   UPDATE <#SESSION.DB/>.dbo.OPORTUNIDADES WITH(ROWLOCK) SET IDUSUARIO=@ELIDUSUARIO, ULTIMAMODIFICACION = GETDATE(),CAMBIOLOCAL=@CAMBIOLOCAL WHERE IDPROSPECTO=@IDPROSPECTO
		 	  IF (@DUENIO <> @ELIDUSUARIO)
	  	  	  BEGIN
				   UPDATE  <#SESSION.DB/>.DBO.prospectos_seguimiento SET ultimamodificacion=GETDATE() WHERE IDSEGUIMIENTO IN (SELECT TOP (10) IDSEGUIMIENTO FROM <#SESSION.DB/>.DBO.prospectos_seguimiento WHERE idprospecto=@IDPROSPECTO ORDER BY 1 DESC)
   	 
	 	 	   	   DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDTABLA = 5 AND IDUSUARIO = @ELIDUSUARIO
	 		   	   INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDTABLA,IDUSUARIO,FECHAHORA) VALUES (5,@ELIDUSUARIO,GETDATE())
				   
				   DELETE FROM <#SESSION.DB/>.dbo.PROSPECTOS_ASIGNADOS WITH(ROWLOCK) WHERE IDUSUARIO=@DUENIO AND IDPROSPECTO=@IDPROSPECTO
	  	  	  END
	 	END
	 END
   
	SET @TO = @TO + 1
END

IF(@TOTALPROSPECTOS > 1)
BEGIN
	EXEC <#SESSION.DB/>.dbo.SP_ENVIAR_CORREO_ASIGNADO_VARIOS @TOTALPROSPECTOS, @ELIDUSUARIO
END

DELETE FROM <#SESSION.DB/>.dbo.MODIFICACIONES WITH (ROWLOCK) WHERE IDTABLA = 4 AND IDEMPRESA = <#SESSION.IDEMPRESA/>
INSERT INTO <#SESSION.DB/>.dbo.MODIFICACIONES  WITH (ROWLOCK) (IDTABLA,IDEMPRESA) VALUES (4 , <#SESSION.IDEMPRESA/>)


END
