//[session.idusuario|Untyped,session.idempresa|Untyped,idorigen|Integer,idprospectos|Text,session.db|Untyped,tkorig|Text,tkp|Text]
-- UPDATE
/*PROTEGIDO*/

DECLARE @IDUSUARIO INT
DECLARE @IDEMPRESA INT
DECLARE @IDORIGEN INT
DECLARE @IDPROSPECTOS VARCHAR(MAX)
DECLARE @FECHA DATETIME
DECLARE @TKP VARCHAR(MAX)
DECLARE @TKORIG VARCHAR(MAX)

SET @TKP = ISNULL(:TKP, '')
SET @TKORIG = ISNULL(:TKORIG, '')

SET @IDUSUARIO = <#SESSION.IDUSUARIO/>
SET @IDEMPRESA = <#SESSION.IDEMPRESA/>

SET @IDORIGEN = :IDORIGEN
SET @IDPROSPECTOS = :IDPROSPECTOS
SET @FECHA = GETDATE()

IF @TKP != '' BEGIN SET @IDPROSPECTOS = <#SESSION.DB>.dbo.obtieneListaIdProspecto(@TKP, @IDEMPRESA) END
IF @TKORIG != '' BEGIN SET @IDORIGEN = <#SESSION.DB>.dbo.obtieneIdOrigen(@TKORIG) END

UPDATE <#SESSION.DB/>.DBO.PROSPECTOS SET IDORIGEN = @IDORIGEN WHERE IDEMPRESA = @IDEMPRESA AND IDPROSPECTO IN(SELECT SPLITVALUE FROM DBO.SPLIT(@IDPROSPECTOS,','))

DELETE FROM <#SESSION.DB/>.DBO.MODIFICACIONES WHERE IDEMPRESA = @IDEMPRESA AND IDTABLA = 4
INSERT INTO <#SESSION.DB/>.DBO.MODIFICACIONES (IDEMPRESA, IDTABLA,FECHAHORA) VALUES(@IDEMPRESA, 4, GETDATE()) 

EXEC <#SESSION.DB/>.DBO.SP_ACTUALIZA_METAS_PROCESO_NUEVO @IDUSUARIO,@FECHA