//[f_usuario|Text,session.gmt|Untyped,session.db|Untyped,session.idusuario|Untyped,session.idempresa|Untyped,]
-- select
DECLARE @SQL VARCHAR(MAX)
DECLARE @CRIT VARCHAR(MAX) SET @CRIT = ISNULL(:F_USUARIO, '')
SET @SQL = '
DECLARE @IDEMPRESA INT = <#SESSION.IDEMPRESA/>
DECLARE @IDUSUARIO INT = <#SESSION.IDUSUARIO/>
DECLARE @DIAS INT = 60

DECLARE @GMT INT

SET @GMT = CAST(''<#SESSION.GMT/>'' AS INT )

DECLARE @TBL TABLE (IDSUCESO INT, IDPROSPECTO INT, TIPO INT)
INSERT INTO @TBL (IDSUCESO, IDPROSPECTO, TIPO)
SELECT MAX(US.IDSUCESO), US.IdproSpecto, us.tipo FROM
<#SESSION.DB/>.dbo.USUARIOS_SUCESOS US
WHERE TIPO IN (select TIPO from <#SESSION.DB/>.dbo.TIPO_SUCESOS where IDUSUARIO = @IDUSUARIO)
AND IDUSUARIO IN (SELECT IDUSUARIO FROM <#SESSION.DB/>.dbo.ObtieneUsuariosAutorizados(@IDUSUARIO))
AND FECHAHORA > GETDATE()- @DIAS
GROUP BY US.IDPROSPECTO, US.TIPO

 
SELECT 
P.TKP, P.NOMBRE, P.APELLIDOS  ,P.DESCARTADO,
SALESUP_CT.dbo.[obtieneFechaRealGMT](@GMT,US.FECHAHORA) AS FECHAHORA, US.TEXTO, US.TIPO, US.IDPROSPECTO, 
 (UU.NOMBRE+'' ''+UU.APELLIDOS) AS EJECUTIVO, US.IDOPORTUNIDAD,(CASE WHEN US.TIPO=24 THEN CONVERT(VARCHAR(10),CIT.FECHA_INICIO,103) ELSE NULL END) AS FECHA_CITA, OP.TKO
FROM <#SESSION.DB/>.dbo.USUARIOS UU  WITH(NOLOCK) 
JOIN <#SESSION.DB/>.dbo.USUARIOS_SUCESOS US  WITH(NOLOCK)  ON US.IDUSUARIO=UU.IDUSUARIO  
  LEFT JOIN <#SESSION.DB/>.dbo.CITAS CIT  WITH(NOLOCK) ON  CIT.IDCITA=US.IDCITA
  LEFT JOIN <#SESSION.DB/>.dbo.OPORTUNIDADES OP WITH(NOLOCK) ON US.IDOPORTUNIDAD=OP.IDOPORTUNIDAD
  LEFT JOIN <#SESSION.DB/>.dbo.PROSPECTOS P WITH(NOLOCK) ON US.IDPROSPECTO = P.IDPROSPECTO

 WHERE IDSUCESO IN (SELECT TOP 10 IDSUCESO FROM @TBL ORDER BY IDSUCESO DESC)
order by IDSUCESO DESC
'
EXEC (@SQL)	