//[listap|Integer,session.idempresa|Untyped,session.idusuario|Untyped,razones|Integer,comentario|Text,session.convertcode|Untyped,tkp|Text,session.db|Untyped,tkrazon|Text]
--insert
DECLARE @LISTA VARCHAR(MAX)
DECLARE @IDEMPRESA INT
DECLARE @IDUSUARIO INT
DECLARE @RAZONES INT
DECLARE @COMENTARIO VARCHAR(258)
DECLARE @CONVERTCODE INT
DECLARE @TKRAZON VARCHAR(MAX)
DECLARE @TKP VARCHAR(MAX)

SET @LISTA = ISNULL(:LISTAP,'') 
SET @IDEMPRESA= CAST('<#SESSION.IDEMPRESA/>' AS INT)
SET @IDUSUARIO   =CAST('<#SESSION.IDUSUARIO/>' AS INT)
SET @RAZONES = ISNULL(:RAZONES,0)
SET @COMENTARIO =  isnull(:COMENTARIO ,'')
SET @CONVERTCODE  = CAST('<#SESSION.CONVERTCODE/>' AS INT)
SET @TKP = ISNULL(:TKP,'')
SET @TKRAZON = ISNULL(:TKRAZON, '0')


IF @TKP != '' BEGIN SET @LISTA = <#SESSION.DB/>.dbo.obtieneIdProspecto(@TKP, @IDEMPRESA) END
IF @TKRAZON != '0' BEGIN SET @RAZONES = <#SESSION.DB/>.dbo.obtieneIdRazonPerdida(@TKRAZON) END

EXEC <#SESSION.DB/>.DBO.SP_DESCARTAR_CLIENTE @IDUSUARIO, @IDEMPRESA, @LISTA, @CONVERTCODE, @COMENTARIO,@RAZONES