//[EMPRESAS|Text,BASE|Text]
--SELECT 
DECLARE @EMPRESAS  VARCHAR(MAX) =  :EMPRESAS
DECLARE @BASE VARCHAR(MAX) =  :BASE
DECLARE @sql VARCHAR(MAX) = 'EXEC '+@BASE+'.DBO.SP_OBTIENE_INFO_EMPRESAS_USO '''+@EMPRESAS+''''

EXEC (@sql)
